> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

---

#  Numpy Assignment - Functions

### Introduction to Numpy

Numpy is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and a variety of mathematical functions to operate on these data structures. Numpy's powerful capabilities make it an essential tool for data analysis, machine learning, and engineering tasks.

In this notebook, we will explore five interesting Numpy functions:
- `dot()`
- `concatenate()`
- `reshape()`
- `array()`
- `eye()`

These functions cover a range of operations from basic array creation and manipulation to more complex matrix operations.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

### Chosen Functions

- `dot()`: Computes the dot product of two arrays.
- `concatenate()`: Joins a sequence of arrays along an existing axis.
- `reshape()`: Gives a new shape to an array without changing its data.
- `array()`: Creates a Numpy array from various data sources.
- `eye()`: Creates a 2-D array with ones on the diagonal and zeros elsewhere (identity matrix).

Now, let's dive into each function with examples to understand their usage and capabilities.

In [1]:
!pip install jovian --upgrade -q

In [1]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.dot # this will be used to multiply two arrays
function2 = np.concatenate  #  this will be used to concatenate two arrays
function3 = np.reshape # this will be used to reshape an array
function4 = np.array # this will be used to create an array
function5 = np.eye # this will be used to create an identity matrix

## Function 1 - np.dot()
Explanation: Computes the dot product of two arrays. For 1-D arrays, it is the inner product of the vectors.
For 2-D arrays, it is equivalent to matrix multiplication.

```python
print("np.dot() Examples")
```

In [7]:
# Example 1: Dot product of 1-D arrays (vectors)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product_1d = np.dot(a, b)
print("Dot product of 1-D arrays:", dot_product_1d)

Dot product of 1-D arrays: 32


- Explanation: The dot product of two 1-D arrays (vectors) is the sum of the products of their corresponding elements.
- In this example, the dot product of [1, 2, 3] and [4, 5, 6] is calculated as (1*4) + (2*5) + (3*6) = 32.

In [8]:
# Example 2: Dot product of 2-D arrays (matrices)
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
dot_product_2d = np.dot(c, d)
print("Dot product of 2-D arrays:\n", dot_product_2d)

Dot product of 2-D arrays:
 [[19 22]
 [43 50]]


- Explanation: The dot product of two 2-D arrays (matrices) is performed as matrix multiplication.
- In this example, the dot product of matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]] results in another matrix.

In [10]:
# Example 3: Dot product involving a 2-D array and a 1-D array

e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([7, 8, 9,5])
dot_product_2d_1d = np.dot(e, f)

print("Dot product of a 2-D array and a 1-D array:\n", dot_product_2d_1d)


ValueError: shapes (2,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

- Explanation: When computing the dot product of a 2-D array and a 1-D array, the 1-D array is treated as a column vector.
- The result is the error because the dimension of 1D array is different in number of columns.

In [11]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "uzairhussain193/assignment-numpy-array-operations" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'

# Function 2: np.concatenate()
Explanation: Joins a sequence of arrays along an existing axis.

```python
print("np.concatenate() Examples")
```

In [12]:
# Example 1: Concatenating 1-D arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated_1d = np.concatenate((a, b))
print("Concatenation of 1-D arrays:", concatenated_1d)

Concatenation of 1-D arrays: [1 2 3 4 5 6]


- Explanation: The concatenation of two 1-D arrays results in a single 1-D array containing all the elements of both arrays.
- In this example, [1, 2, 3] and [4, 5, 6] are concatenated to form [1, 2, 3, 4, 5, 6].

In [13]:
# Example 2: Concatenating 2-D arrays along axis 0 (rows)

c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
concatenated_2d_axis0 = np.concatenate((c, d), axis=0)
print("Concatenation of 2-D arrays along axis 0:\n", concatenated_2d_axis0)

Concatenation of 2-D arrays along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


- Explanation: Concatenating 2-D arrays along axis 0 stacks them vertically.
- In this example, [[1, 2], [3, 4]] and [[5, 6], [7, 8]] are concatenated along axis 0 to form [[1, 2], [3, 4], [5, 6], [7, 8]].

In [17]:
# Example 3: Concatenating 2-D arrays along axis 1 (columns)
c = np.array([[1, 2], [3, 4,],[5,6]])
d = np.array([[5, 6], [7, 8]])
concatenated_2d_axis1 = np.concatenate((c, d), axis=1)
print("Concatenation of 2-D arrays along axis 1:\n", concatenated_2d_axis1)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

#### Detailed Explanation:
In the provided code:
```python
c = np.array([[1, 2], [3, 4], [5, 6]])
d = np.array([[5, 6], [7, 8]])
concatenated_2d_axis1 = np.concatenate((c, d), axis=1)
print("Concatenation of 2-D arrays along axis 1:\n", concatenated_2d_axis1)
```

c is a 3x2 array:
```python
[[1, 2],
 [3, 4],
 [5, 6]]
```


d is a 2x2 array:
```python
[[5, 6],
 [7, 8]]
```

Attempting to concatenate these arrays along axis=1 (columns) will result in an error because:

- Array c has 3 rows.
- Array d has 2 rows.
For concatenation along columns (axis=1), both arrays must have the same number of rows.

Some closing comments about when to use this function.

In [18]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "uzairhussain193/assignment-numpy-array-operations" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'

# Function 3: np.reshape()

- Explanation: The np.reshape() function changes the shape of an array without modifying its data. The total number of elements must remain the same.

```python
print("np.reshape() Examples")
```

In [19]:
# Example 1: Reshaping a 1-D array to a 2-D array

a = np.array([1, 2, 3, 4, 5, 6])
reshaped_1d_to_2d = np.reshape(a, (2, 3))
print("Reshaped 1-D array to 2-D array:\n", reshaped_1d_to_2d)


Reshaped 1-D array to 2-D array:
 [[1 2 3]
 [4 5 6]]


- The 1-D array 'a' with 6 elements is reshaped into a 2-D array with 2 rows and 3 columns.

In [20]:
# Example 2: Reshaping a 2-D array to a 3-D array

b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
reshaped_2d_to_3d = np.reshape(b, (2, 2, 2))
print("Reshaped 2-D array to 3-D array:\n", reshaped_2d_to_3d)


Reshaped 2-D array to 3-D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- The 2-D array 'b' with shape (4, 2) is reshaped into a 3-D array with shape (2, 2, 2).

In [21]:

# Example 3 - Create a 1-D array with 6 elements and reshape it
a = np.array([1, 2, 3, 4, 5, 6])

# Attempt to reshape this array to a 2x4 array
# This should throw an error because the total number of elements (6) does not match the new shape (2*4=8)
reshaped_invalid = np.reshape(a, (2, 4))
print("Reshaped 1-D array to 2x4 array:\n", reshaped_invalid)

ValueError: cannot reshape array of size 6 into shape (2,4)

#### Explanation
Original Array: The array a has 6 elements.

`a = np.array([1, 2, 3, 4, 5, 6])`

- Invalid Reshape Attempt: We attempt to reshape this array into a shape of (2, 4).


`reshaped_invalid = np.reshape(a, (2, 4))`
- Reason for Error: The total number of elements in the original array (6) does not match the total number of elements required by the new shape (2 * 4 = 8).

- Error Message: The np.reshape() function will throw a ValueError indicating that it cannot reshape an array of size 6 into shape (2, 4).

In [22]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "uzairhussain193/assignment-numpy-array-operations" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'

## Function # 4. np.array()

- Explanation: The np.array() function creates a Numpy array from various data sources like lists or tuples. 
- It is a fundamental function to initialize arrays in Numpy.

```python
print("np.array() Examples")
```

In [23]:
# Example 1: Creating an array from a list
# The list 'list_data' is converted into a Numpy array.
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Array from list:", array_from_list)


Array from list: [1 2 3 4 5]


- Explanation: Creates an array from a Python list. This is a basic and common way to initialize a Numpy array from list data.

In [24]:
# Example 2: Creating an array from a tuple
# The tuple 'tuple_data' is converted into a Numpy array.
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print("Array from tuple:", array_from_tuple)


Array from tuple: [ 6  7  8  9 10]


- Explanation : Creates an array from a Python tuple. Similar to the list, this shows the flexibility of np.array() in handling different data types.

In [26]:

# Example 3: Creating a 2-D array from a list of lists
# The list of lists 'list_of_lists' is converted into a 2-D Numpy array.
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 9]]
array_from_list_of_lists = np.array(list_of_lists)
print("2-D array from list of lists:\n", array_from_list_of_lists)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

- Explanation:
In the code:

```python
# Example 3: Creating a 2-D array from a list of lists
# The list of lists 'list_of_lists' is converted into a 2-D Numpy array.
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 9]]
array_from_list_of_lists = np.array(list_of_lists)
print("2-D array from list of lists:\n", array_from_list_of_lists)
```

- The inner lists in list_of_lists have different lengths: [1, 2, 3] has 3 elements, [4, 5, 6] has 3 elements, and [7, 9] has 2 elements.
- Numpy arrays require that all rows in a 2-D array have the same number of columns.
- Because the lengths are inconsistent, Numpy will create an array of dtype=object instead of a proper 2-D array, which is not usually the desired outcome.

In [27]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "uzairhussain193/assignment-numpy-array-operations" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'

## Function # 5. np.eye()

- Explanation: The np.eye() function creates a 2-D array with ones on the diagonal and zeros elsewhere. This is often referred to as an identity matrix.

```python
print("np.eye() Examples")

In [28]:
# Example 1: Creating a 3x3 identity matrix
# A 3x3 identity matrix has ones on the diagonal and zeros elsewhere.
identity_matrix_3x3 = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix_3x3)


3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- Explanation : Creates a 3x3 identity matrix, which is a square matrix with ones on the diagonal and zeros elsewhere. Identity matrices are commonly used in linear algebra.

In [29]:
# Example 2: Creating a 4x4 identity matrix
# A 4x4 identity matrix has ones on the diagonal and zeros elsewhere.
identity_matrix_4x4 = np.eye(4)
print("4x4 identity matrix:\n", identity_matrix_4x4)


4x4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


- Explanation : Creates a 4x4 identity matrix, showing the ability to generate larger identity matrices.

In [30]:
# Example 3: Creating a 3x3 identity matrix with an offset diagonal
identity_matrix_offset = np.eye(3, k=1)
print("3x3 identity matrix with offset diagonal:\n", identity_matrix_offset)

3x3 identity matrix with offset diagonal:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]



- The identity matrix with an offset diagonal is created using the 'k' parameter.
- 'k=1' means the diagonal is offset by one position above the main diagonal.

Some closing comments about when to use this function.

In [31]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "uzairhussain193/assignment-numpy-array-operations" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [32]:
jovian.commit(filename="assignment-numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "uzairhussain193/assignment-numpy-array-operations" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/uzairhussain193/assignment-numpy-array-operations


'https://jovian.com/uzairhussain193/assignment-numpy-array-operations'